name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # dispara o deploy sempre que houver push na main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js (opcional, só se precisar de build)
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies (opcional, só se precisar de build)
        run: |
          cd revitalize_app
          npm install

      # Caso você não precise de build, pode pular as etapas de Node.js e instalar

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./revitalize_app   # pasta que contém seu index.html
          keep_files: true
